name: Install Dependencies  
  
on: [push]  
  
jobs:  
  install-deps:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout Code  
      uses: actions/checkout@v2  
  
    - name: Update Package Lists  
      run: sudo apt update -y  
  
    - name: Upgrade Packages  
      run: sudo apt full-upgrade -y  
  
    - name: Install Dependencies  
      run: |  
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \  
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \  
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \  
        libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \  
        mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \  
        libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip \  
        vim wget xmlto xxd zlib1g-dev python3-setuptools
    - name: 触发构建
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: 编译openwrt
